/**
 * @license
 *
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import {
  AILabel,
  AILabelActions,
  AILabelContent,
  Button,
  IconButton,
  Tag,
} from '@carbon/react';
import {
  AiGenerate,
  ArrowRight,
  Chat,
  Checkmark,
  ChevronDown,
  ChevronUp,
  Copy,
  Download,
  ThumbsDown,
  ThumbsUp,
} from '@carbon/icons-react';
import { CommentComposer } from '../CommentComposer/CommentComposer';
import { CommentThread } from '../CommentThread/CommentThread';
import { MarkdownRenderer } from '../MarkdownRenderer/MarkdownRenderer';
import { SelectionMenu } from '../SelectionMenu/SelectionMenu';
import { useMarkdownTile } from '../../hooks/useMarkdownTile';
import type { MarkdownTileProps, MarkdownTileVariant } from '../../types';

const variantLabels: Record<MarkdownTileVariant, string> = {
  plan: 'Plan',
  reference: 'Reference',
  insight: 'Insight',
};

export const MarkdownTile = ({
  actionState,
  aiExplainabilityDescription,
  aiExplainabilityTitle = 'AI explained',
  aiLabel = true,
  aiLabelText = 'AI',
  annotations,
  annotatable = false,
  approveActionLabel = 'Approve plan',
  className,
  collapseLabel = 'Collapse',
  content,
  defaultActionState = 'idle',
  defaultAnnotations = [],
  doneActionLabel,
  downloadFileName = 'markdown-tile.md',
  expandPillLabel,
  initiallyExpanded = false,
  onActionStateChange,
  onAnnotationsChange,
  onCopy,
  onDownload,
  onFeedback,
  onPrimaryAction,
  secondaryActions = [],
  subtitle,
  title,
  updateActionLabel = 'Update plan',
  variant = 'plan',
  ...rest
}: MarkdownTileProps) => {
  const {
    activeAnnotationId,
    blockClass,
    composer,
    contentRef,
    copied,
    expanded,
    handleAnnotate,
    handleCopy,
    handleDeleteComment,
    handleDownload,
    handleFeedback,
    handlePrimaryAction,
    handleSelectAnnotation,
    handleSubmitComment,
    hasComments,
    isApproved,
    isTouch,
    resolvedAnnotations,
    selectionMenu,
    setComposer,
    setExpanded,
    setThreadOpen,
    threadOpen,
    tileRef,
  } = useMarkdownTile({
    actionState,
    annotations,
    annotatable,
    content,
    defaultActionState,
    defaultAnnotations,
    downloadFileName,
    initiallyExpanded,
    onActionStateChange,
    onAnnotationsChange,
    onCopy,
    onDownload,
    onFeedback,
    onPrimaryAction,
  });

  // Comments turn the plan action into an update flow; the done label mirrors
  // whichever path the user completed.
  const primaryLabel = hasComments ? updateActionLabel : approveActionLabel;
  const finalDoneLabel =
    doneActionLabel ??
    (hasComments
      ? 'Updates submitted'
      : approveActionLabel.replace(/^Approve/, 'Approved'));

  const classes = [
    blockClass,
    `${blockClass}--${variant}`,
    expanded ? `${blockClass}--expanded` : `${blockClass}--collapsed`,
    aiLabel ? `${blockClass}--ai` : '',
    hasComments ? `${blockClass}--has-comments` : '',
    isApproved ? `${blockClass}--approved` : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <article {...rest} className={classes} ref={tileRef}>
      {aiLabel ? (
        <div className={`${blockClass}__rim`} aria-hidden="true" />
      ) : null}

      <div className={`${blockClass}__inner`}>
        <header className={`${blockClass}__header`}>
          <div className={`${blockClass}__label-row`}>
            <Tag
              className={`${blockClass}__type-label`}
              decorator={variant === 'insight' ? <AiGenerate /> : undefined}
              size="sm"
              type={
                variant === 'plan'
                  ? 'blue'
                  : variant === 'insight'
                  ? 'purple'
                  : 'gray'
              }>
              {variantLabels[variant]}
            </Tag>
            {/* Carbon AI disclosure stays near the variant label so the source
                and annotation affordance are discoverable before reading. */}
            {aiLabel ? (
              <AILabel autoAlign aiText={aiLabelText} size="xs">
                <AILabelContent>
                  <div className={`${blockClass}__ai-content`}>
                    <p className={`${blockClass}__ai-kicker`}>
                      Generated content
                    </p>
                    <h2>{aiExplainabilityTitle}</h2>
                    <p>
                      {aiExplainabilityDescription ??
                        'This content was generated by an AI model and may be inaccurate or incomplete.'}
                    </p>
                    {annotatable ? (
                      <p>
                        Highlight a passage to leave feedback for the next
                        revision.
                      </p>
                    ) : null}
                    <AILabelActions>
                      <Button kind="ghost" size="sm">
                        View details
                      </Button>
                    </AILabelActions>
                  </div>
                </AILabelContent>
              </AILabel>
            ) : null}
            {hasComments ? (
              <span
                className={`${blockClass}__comment-badge`}
                title={`${resolvedAnnotations.length} comments`}>
                <Chat size={11} />
                <span>{resolvedAnnotations.length}</span>
              </span>
            ) : null}
          </div>

          <div className={`${blockClass}__actions`}>
            {secondaryActions.map((action, index) => (
              <IconButton
                align="bottom"
                kind="ghost"
                key={`${action.label}-${index}`}
                label={action.label}
                onClick={action.onClick}
                size="sm">
                {action.icon}
              </IconButton>
            ))}
            <IconButton
              align="bottom"
              kind="ghost"
              label="Download markdown"
              onClick={handleDownload}
              size="sm">
              <Download />
            </IconButton>
            <IconButton
              align="bottom"
              kind="ghost"
              label={copied ? 'Copied' : 'Copy markdown'}
              onClick={handleCopy}
              size="sm">
              {copied ? <Checkmark /> : <Copy />}
            </IconButton>
            <IconButton
              align="bottom"
              kind="ghost"
              label="Good response"
              onClick={() => handleFeedback('positive')}
              size="sm">
              <ThumbsUp />
            </IconButton>
            <IconButton
              align="bottom"
              kind="ghost"
              label="Bad response"
              onClick={() => handleFeedback('negative')}
              size="sm">
              <ThumbsDown />
            </IconButton>
          </div>
        </header>

        <div className={`${blockClass}__content`} ref={contentRef}>
          {title || subtitle ? (
            <div className={`${blockClass}__title-block`}>
              {title ? (
                <h2 className={`${blockClass}__title`}>{title}</h2>
              ) : null}
              {subtitle ? (
                <p className={`${blockClass}__subtitle`}>{subtitle}</p>
              ) : null}
            </div>
          ) : null}

          {/* The renderer marks block positions for annotation lookup; the
              overlay controls use the same content bounds for positioning. */}
          <div className={`${blockClass}__markdown`}>
            <MarkdownRenderer
              activeAnnotationId={activeAnnotationId}
              annotations={resolvedAnnotations}
              blockClass={blockClass}
              content={content}
              onAnnotationSelect={handleSelectAnnotation}
            />
          </div>

          {!expanded ? (
            <div className={`${blockClass}__fade`} aria-hidden="true" />
          ) : null}

          {selectionMenu && expanded ? (
            <SelectionMenu
              blockClass={blockClass}
              isTouch={isTouch}
              onAnnotate={handleAnnotate}
              position={selectionMenu}
            />
          ) : null}

          {composer && expanded ? (
            <CommentComposer
              blockClass={blockClass}
              composer={composer}
              onCancel={() => setComposer(null)}
              onSubmit={handleSubmitComment}
            />
          ) : null}
        </div>

        {/* Comment threads are only shown when expanded so inline annotations
            and the review panel stay in sync with the readable markdown. */}
        {expanded && annotatable && hasComments ? (
          <CommentThread
            activeAnnotationId={activeAnnotationId}
            annotations={resolvedAnnotations}
            blockClass={blockClass}
            onDelete={handleDeleteComment}
            onSelect={handleSelectAnnotation}
            onToggle={() => setThreadOpen(!threadOpen)}
            open={threadOpen}
          />
        ) : null}

        {/* The footer owns the reveal control and the plan-only approval state. */}
        <footer className={`${blockClass}__footer`}>
          <Button
            className={`${blockClass}__toggle-button`}
            kind="tertiary"
            onClick={() => setExpanded(!expanded)}
            renderIcon={expanded ? ChevronUp : ChevronDown}
            size="sm"
            type="button">
            {expanded
              ? collapseLabel
              : expandPillLabel ?? `Show full ${variant}`}
          </Button>

          {variant === 'plan' ? (
            <Button
              className={[
                `${blockClass}__primary-button`,
                isApproved ? `${blockClass}__primary-button--done` : '',
                hasComments && !isApproved
                  ? `${blockClass}__primary-button--update`
                  : '',
              ]
                .filter(Boolean)
                .join(' ')}
              disabled={isApproved}
              kind={hasComments && !isApproved ? 'secondary' : 'primary'}
              onClick={handlePrimaryAction}
              renderIcon={isApproved ? Checkmark : ArrowRight}
              size="sm"
              type="button">
              {isApproved ? finalDoneLabel : primaryLabel}
            </Button>
          ) : null}
        </footer>
      </div>
    </article>
  );
};
